game:GetService("Players").LocalPlayer.PlayerGui.WarningGui.Frame.Visible = false
game:GetService("Players").LocalPlayer.PlayerGui.WarningGui.Frame.ChildAdded:Connect(function(v)
v:Destroy()
end)
game:GetService("Players").LocalPlayer:SetAttribute("SoundsEnabled", false)
game:GetService("ReplicatedStorage").RemoteEvents.UpdateEggStockGui.OnClientEvent:Connect(function()
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("AncientEgg","Cash")
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("CursedEgg","Cash")
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("VoidEgg","Cash")
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("ChaosEgg","Cash")
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("AbyssEgg","Cash")
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("NatureEgg","Cash")
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("RainbowEgg","Cash")
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("GlitchEgg","Cash")
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("SeraphicEgg","Cash")
game:GetService("ReplicatedStorage").RemoteEvents.BuyEgg:FireServer("EmpyreanEgg","Cash")
end)
